### ISSUE TITLE
HeadSettings available in TR

### ISSUE THREAD

**Issue by JebEddun** [ducakar/TextureReplacer#13]
I've noticed that TRR had an option to change eyeball color. Is this available in TR and more specificly can it be available for specific class of Kerbals like for the suits?

I'm kinda confused as why there was a TRR also...

Thanks

**Comment by ducakar** [comment]
It will be added in TR 3.5.

TRR is there because I was (almost) absent from KSP community for a few years and stopped playing KSP, so I also lost interest in developing and maintaining TR. When I started playing KSP again, I didn't like TRR (mostly feature creep), so I continued developing TR.
