### ISSUE TITLE
Futuristic Helmet not reading Emissive texture

### ISSUE THREAD

**Issue by Jiraiyah** [ducakar/TextureReplacer#17]
Take a look at these pictures

https://i.imgur.com/g2Z4RXn.png

as you see I have few places on the suit's front side with emission, this is working, but the same texture is not adding up to helmet

https://i.imgur.com/jDXV1yz.png

the leaf icons on the helmet has conterpart in the emissive texture, but they are not lighting up

https://i.imgur.com/0Ia1ode.png

looks like the helmet is reading the emissive texture from the internal texture in assets file from squad?

**Comment by ducakar** [comment]
You're right, I forgot to set emissive texture for helmet and neck ring. I'll release 4.1.1 to fix it. 599f1c3c76136d078952090874fac4068527429f
