### ISSUE TITLE
Custom suitcombos incorrect texture with TR

### ISSUE THREAD

**Issue by Zorbaq** [ducakar/TextureReplacer#19]
TR seems to be mangling custom suits using the recently added stock feature (suitcombo definitions - tested with Phoenix Industries mod). Is there a way to get these working together? Alternatively, would it be possible to introduce an option to have TR don't touch the suits in any way and let it handle the skins only?

**Comment by ducakar** [comment]
You can disable suit personalisation in TR GUI.

**Comment by Zorbaq** [comment]
Thanks, that's the workaround I was looking for!
