### ISSUE TITLE
Framerate drop

### ISSUE THREAD

**Issue by mwhite75** [ducakar/TextureReplacer#5]
Using this mod, I built an 8 part rocket, took it off, splashed it down in the water off of KSC.  EVA'ed in IVA suit, 110+ FPS.  Switched to EVA suit, FPS drops to 20.  Switch back, 110 FPS.  Removed mod, EVA in EVA suit, same scenario, 110 FPS.  There appears to be a huge framerate hit somewhere in what you're doing with the EVA suit.

**Comment by ducakar** [comment]
Check your log, something must be crashing every frame, probably reflections.

**Comment by ducakar** [comment]
Reporter failed to send logs, inactive for too long. Closing.
